name: FwHumanStratego
version: 1.0.0
main: com.gmail.samueler53.fwhumanstratego.FwHumanStratego
api-version: 1.16
depend:
  - FWKotlinDeps
commands:
  humanstratego:
    permission: humanstratego.usercommand
    description: Comando base
    aliases: [hs,humanstratego]
    usage: /hs [ join | team | leave | role | info ]
    permission-message: Non hai i permessi per usare questo comando
  humanstrategoadmin:
    permission: humanstratego.admincommand
    description: Comando admin
    aliases: [hsa,humanstrategoadmin]
    usage: /hsa [ arenas | create | discard | info | modify | reload | remove | set | start | stop ]
    permission-message: Non hai i permessi per usare questo comando