name: FwHumanStratego
version: 1.0.0
main: com.gmail.samueler53.fwhumanstratego.FwHumanStratego
api-version: 1.16
depend:
  - FWKotlinDeps
commands:
  humanstratego:
    permission: humanstratego.usercommand
    description: Comando base
    aliases: hs
    usage: test
    permission-message: Non hai i permessi per usare questo comando
  humanstrategoadmin:
    permission: humanstratego.admincommand
    description: Comando admin
    aliases: hsa
    usage: test
    permission-message: Non hai i permessi per usare questo comando